services:
  web:
    build:
      context: ./API 
      dockerfile: Dockerfile что такое 
    ports:
      - "80:80"
    depends_on:
      - database
  database:
    image: postgres:16
    restart: always
    environment:                  # это перменные окружения для базы данных (штуки которые читает база данных прежде чем запуститься) их можно менять 
      POSTGRES_USER: 'admin'      # это имя юзера, для подключения к базе, его можно поменять на любое другое 
      POSTGRES_PASSWORD: 'admin'  # это пароль, для подключения к базе, его можно поменять на любой другое
      POSTGRES_DB: 'production'   # это имя базы данных которая создаться при запуске базы, его можно поменять
    networks:
      - backend
    ports:
      - "5431:5432"               # База данных будет подниматься на порту 5431, лучше это не трогайте 
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
minio:
  image: minio/minio
  env_file:
    - .env
  ports:
    - "9000:9000"
    - "9001:9001"
  volumes:
    - datastore:/data
  networks:
    - backend
  command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb minio/${MINIO_BUCKET};
      /usr/bin/mc policy set public minio/${MINIO_BUCKET};
      exit 0;
      "
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - backend

volumes:
  database-pg: